### ISSUE TITLE
Relayer incorrectly requiring CMC key import

### ISSUE THREAD

**Issue by BrendanChou** [makerdao/oracles-v2#36]
https://github.com/makerdao/oracles-v2/blob/72c8d0b93d67ae7a45988c45953e1a8e6959263b/omnia/config.sh#L29

Relayers do not need a CMC key as far as I am aware. It should only be imported if the mode is FEED

**Comment by BrendanChou** [comment]
I get `Error - Coinmarketcap API Key is invalid.` as an error in Omnia when running in relayer mode if I don't include it as a valid api key in my relayer config

**Comment by icetan** [comment]
Thanks for reporting this! A fix is on its way.
